version: '3.8'

services:
  web:
    container_name: ocean-eco-watch
    build: .
    restart: always
    networks:
      - traefik
    ports:
      - 3002:3000
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.services.oceanecowatch-org.loadbalancer.server.port=3000'
      - 'traefik.http.routers.oceanecowatch-org.rule=Host(`oceanecowatch.org`) || Host(`www.oceanecowatch.org`)'
      - 'traefik.http.routers.oceanecowatch-org.entrypoints=websecure'
      - 'traefik.http.routers.oceanecowatch-org.tls.certresolver=letsencrypt'
networks:
  traefik:
    external: true
