// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'de'
	| 'en'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	/**
	 * t​h​e​ ​o​c​e​a​n​ ​e​c​o​ ​w​a​t​c​h​ ​u​s​e​s​ ​s​a​t​t​e​l​i​e​t​ ​i​m​a​g​e​ ​r​e​c​o​g​n​i​t​i​o​n​ ​t​e​c​h​n​o​l​o​g​i​y​ ​t​o​ ​h​e​l​p​ ​y​o​u​ ​f​i​s​h​ ​p​l​a​s​t​i​c
	 */
	HI: string
}

export type TranslationFunctions = {
	/**
	 * the ocean eco watch uses satteliet image recognition technologiy to help you fish plastic
	 */
	HI: () => LocalizedString
}

export type Formatters = {}
